version: "3.9"
services:
  taskflow-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
      - redis-stack-svc
    volumes: 
      - ../..:/app
    ports:
      - "127.0.0.1:3000:3000" # React
      - "127.0.0.1:5000:5000" # NodeJs
      - "127.0.0.1:5001:5001" # Hub
      - "127.0.0.1:5002:5002" # RxJS
      - "127.0.0.1:5003:5003" # RxJS Coprocessor
    networks:
      - taskflow

  mongodb:
    # Had issues with docker on MacOS with the latest so went back to 4.4
    #image: mongodb/mongodb-community-server:latest
    image: mongodb/mongodb-community-server:4.4.22-ubuntu2004
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb-data:/data/db
    networks:
      - taskflow

  redis-stack-svc:
    image: redis/redis-stack:latest
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    # Writes to disk every 10 minutes if at least 1 change.
    environment:
      - REDIS_ARGS=--save 600 1
    volumes:
      - redis-data:/data
    networks:
      - taskflow

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.2
    volumes:
    - weaviate-data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'weaviate1'
    networks:
      - taskflow

  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured:latest
    networks:
      - taskflow

volumes:
  mongodb-data:
  redis-data:
  weaviate-data:

networks:
    taskflow:
       external: true