FROM node:18-buster-slim

WORKDIR /app

# Set bash as the default shell
SHELL ["/bin/bash", "-c"]
ENV SHELL /bin/bash

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y bash git python3 python3-pip python3-dev build-essential screen procps vim wget

EXPOSE 3000
EXPOSE 5000
EXPOSE 5001

COPY entrypoint-react.sh /entrypoint-react.sh
RUN chmod 755 /entrypoint-react.sh
COPY entrypoint-nodejs.sh /entrypoint-hub.sh
RUN chmod 755 /entrypoint-hub.sh
COPY entrypoint-nodejs.sh /entrypoint-rxjs.sh
RUN chmod 755 /entrypoint-rxjs.sh
COPY entrypoint-nodejs.sh /entrypoint-rxjscopro.sh
RUN chmod 755 /entrypoint-rxjscopro.sh
COPY entrypoint-nodejs.sh /entrypoint-rxjsnodejs.sh
RUN chmod 755 /entrypoint-rxjsnodejs.sh

ENTRYPOINT ["/entrypoint.sh"]
