version: "3.9"
services:
  taskflow-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    depends_on:
      - mongodb
    volumes: 
      - ../..:/app
      - ./root:/root # For SSH and gitconfig
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:9229:9229" # debug of hub
      - "127.0.0.1:9230:9230" # debug of nodejs
      - "127.0.0.1:9231:9231" # debug of rxjs
    networks:
      - web-proxy

  mongodb:
    # Had issues with docker on MacOS with the latest so went back to 4.4
    #image: mongodb/mongodb-community-server:latest
    image: mongodb/mongodb-community-server:4.4.22-ubuntu2004
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    networks:
      - web-proxy

  redis-stack-svc:
    image: redis/redis-stack:latest
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    # Writes to disk every 10 minutes if at least 1 change.
    environment:
      - REDIS_ARGS=--save 600 1
      # Could not get this working with a proxy maybe not supporting a proxy path
    volumes:
      - my-redis-data:/data
    networks:
      - web-proxy

volumes:
  mongodbdata:
  my-redis-data:

networks:
    web-proxy:
       external: true
