FROM node:18-buster-slim

WORKDIR /app

# Set bash as the default shell
SHELL ["/bin/bash", "-c"]
ENV SHELL /bin/bash

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y bash git python3 python3-pip build-essential screen procps vim wget

RUN pip3 install rx redis aioredis

EXPOSE 3000
EXPOSE 5000
EXPOSE 5001

COPY entrypoint-react.sh /entrypoint-react.sh
RUN chmod 755 /entrypoint-react.sh
COPY entrypoint-hub.sh /entrypoint-hub.sh
RUN chmod 755 /entrypoint-hub.sh
COPY entrypoint-hub-consumer.sh /entrypoint-hub-consumer.sh
RUN chmod 755 /entrypoint-hub-consumer.sh
COPY entrypoint-hub-coprocessor.sh /entrypoint-hub-coprocessor.sh
RUN chmod 755 /entrypoint-hub-coprocessor.sh
COPY entrypoint-processor-consumer.sh /entrypoint-processor-consumer.sh
RUN chmod 755 /entrypoint-processor-consumer.sh

ENTRYPOINT ["/entrypoint.sh"]
