version: "3.9"
services:
  taskflow-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes: 
      - ../..:/app
    ports:
      - "127.0.0.1:3000:3000" # React
      - "127.0.0.1:5000:5000" # NodeJs
      - "127.0.0.1:5001:5001" # Hub
      - "127.0.0.1:5002:5002" # RxJS
      - "127.0.0.1:5003:5003" # RxJS Coprocessor
    networks:
      - taskflow

  mongodb:
    # Had issues with docker on MacOS with the latest so went back to 4.4
    #image: mongodb/mongodb-community-server:latest
    image: mongodb/mongodb-community-server:4.4.22-ubuntu2004
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    networks:
      - taskflow

  redis-stack-svc:
    image: redis/redis-stack:latest
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    # Writes to disk every 10 minutes if at least 1 change.
    environment:
      - REDIS_ARGS=--save 600 1
    volumes:
      - my-redis-data:/data
    networks:
      - taskflow

volumes:
  mongodbdata:
  my-redis-data:

networks:
    taskflow:
       external: true